name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - name: Setup Swift
      uses: fwal/setup-swift@v1.14.0
    - name: Get swift version
      run: swift --version # Swift 5.1.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
